services:
  qr-generator:
    build: .
    container_name: qr-generator-app
    # Remove host port publishing (optional but recommended)
    ports:
      - "9001:5000"
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=5000
      - PYTHONUNBUFFERED=1
      - GUNICORN_WORKERS=2
      - GUNICORN_LOG_LEVEL=info
    volumes:
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Ensure Traefik uses the correct Docker network
      - "traefik.docker.network=proxy"
      # HTTP router
      - 'traefik.http.routers.qr_jo3_dev-http.rule=Host(`qr.jo3.dev`)'
      - "traefik.http.routers.qr_jo3_dev-http.entrypoints=web"
      - "traefik.http.routers.qr_jo3_dev-http.service=qr_jo3_dev"
      - "traefik.http.services.qr_jo3_dev.loadbalancer.server.port=5000"

networks:
  default:
    name: proxy